services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ppworld-backend
    ports:
      - "8090:8000"
    networks:
      - shared_proxy
    volumes:
      - ./prod_data:/app/data
    restart: unless-stopped
    command: python backend/main.py

  data:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./prod_data:/app/data
    command: python data/main.py

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ppworld-frontend
    ports:
      - "3090:3000"
    networks:
      - shared_proxy
    restart: unless-stopped

networks:
  shared_proxy:
    external: true
